'use strict';
// Local recorded score, soft source crossfades and bounded voices. Safari unlock
// remains synchronous with the initiating tap; no Audio element volume assumptions.
class JourneyAudio {
 constructor(url,onError){Object.assign(this,{url,onError,context:null,buffer:null,source:null,outgoing:null,offset:0,startedAt:0,wantsMusic:false,loading:null,trackEpoch:0,loop:true,musicVolume:.65,effectsVolume:.5,muted:false,failed:false,lastLevel:-1,lastEffects:-1,duckUntil:0,world:0,mood:'travel',lastCollect:-10});this.samples={};this.fx=new Set();this.retiring=new Set();}
 unlock(){try{
  if(!this.context){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const c=this.context=new AC();this.music=c.createGain();this.music.gain.value=0;this.music.connect(c.destination);this.effects=c.createGain();this.effects.gain.value=this.muted?0:this.effectsVolume;this.effects.connect(c.destination);this.loadSamples();this.createAmbience();}
  const c=this.context;if(c.state!=='running')c.resume().then(()=>{if(this.wantsMusic)this.play();}).catch(()=>{});
  const s=c.createBufferSource();s.buffer=c.createBuffer(1,1,c.sampleRate);s.connect(this.effects);s.start();s.onended=()=>s.disconnect();
  if(!this.buffer&&!this.loading){const epoch=this.trackEpoch,url=this.url;this.abort?.abort();this.abort=new AbortController();this.loading=fetch(url,{signal:this.abort.signal}).then(r=>{if(!r.ok)throw Error('Music unavailable');return r.arrayBuffer();}).then(b=>c.decodeAudioData(b)).then(b=>{if(epoch!==this.trackEpoch)return;this.buffer=b;this.failed=false;if(this.wantsMusic)this.play();}).catch(e=>{if(epoch!==this.trackEpoch||e.name==='AbortError')return;this.failed=true;this.retire(this.outgoing,.3);this.outgoing=null;this.onError?.();}).finally(()=>{if(epoch===this.trackEpoch)this.loading=null;});}
 }catch{this.failed=true;this.onError?.();}}
 setTrack(url){this.loop=true;if(this.url===url)return;this.abort?.abort();this.retire(this.outgoing,.08);this.outgoing=this.source;this.source=null;this.trackEpoch++;this.url=url;this.buffer=null;this.loading=null;this.offset=0;this.failed=false;}
 play(reset=false){this.wantsMusic=true;if(reset){this.stopSource();this.offset=0;}if(this.muted)return;if(!this.context||!this.buffer)this.unlock();const c=this.context;if(!c||!this.buffer||c.state!=='running'||this.source)return;const s=c.createBufferSource(),g=c.createGain();s.buffer=this.buffer;s.loop=this.loop;s._gain=g;g.gain.setValueAtTime(0,c.currentTime);g.gain.linearRampToValueAtTime(1,c.currentTime+.65);s.connect(g);g.connect(this.music);s.start(0,this.offset%this.buffer.duration);this.startedAt=c.currentTime;this.source=s;this.retire(this.outgoing,.75);this.outgoing=null;s.onended=()=>{s.disconnect();g.disconnect();this.retiring.delete(s);if(this.source!==s)return;this.source=null;this.offset=0;if(!s.loop)this.wantsMusic=false;};}
 retire(s,seconds=.06){if(!s||!this.context)return;const t=this.context.currentTime;try{const g=s._gain?.gain;if(g){g.cancelScheduledValues(t);g.setValueAtTime(g.value,t);g.linearRampToValueAtTime(0,t+seconds);}this.retiring.add(s);s.stop(t+seconds+.015);s.onended=()=>{s.disconnect();s._gain?.disconnect();this.retiring.delete(s);};}catch{this.retiring.delete(s);}}
 stopSource(){if(this.source){if(this.buffer)this.offset=(this.offset+this.context.currentTime-this.startedAt)%this.buffer.duration;this.retire(this.source,.02);this.source=null;}}
 pause(){this.wantsMusic=false;this.stopSource();this.retire(this.outgoing,.03);this.outgoing=null;for(const s of this.retiring)this.retire(s,.03);this.stopEffects();if(this.music){const t=this.context.currentTime;this.music.gain.cancelScheduledValues(t);this.music.gain.setTargetAtTime(0,t,.02);this.ambientGain.gain.setTargetAtTime(0,t,.02);this.lastLevel=0;}}
 victory(){this.pause();this.setTrack('assets/victory.mp3?v=touchsound15b');this.loop=false;this.unlock();this.play(true);}
 mix({music,effects,muted}){this.musicVolume=music;this.effectsVolume=effects;this.muted=muted;if(this.effects)this.effects.gain.setTargetAtTime(muted?0:effects,this.context.currentTime,.025);if(muted){this.stopSource();this.retire(this.outgoing,.02);this.outgoing=null;for(const s of this.retiring)this.retire(s,.02);this.stopEffects();if(this.ambientGain)this.ambientGain.gain.setTargetAtTime(0,this.context.currentTime,.015);}else if(this.wantsMusic){this.unlock();this.play();}}
 setScene(world){this.world=world;this.mood='travel';this.lastCollect=-10;if(this.ambientFilter){this.ambientFilter.type=world===1?'lowpass':'bandpass';this.ambientFilter.frequency.setTargetAtTime([520,750,1300,2200,850,600][world],this.context.currentTime,.6);}}
 setMood(kind){this.mood=['reward','treasure'].includes(kind)?'rest':kind==='final'?'final':'travel';}
 update(active,dash){if(!this.context)return;const t=this.context.currentTime;const level=active&&!this.muted?this.musicVolume*.92*(t<this.duckUntil?.46:1)*(this.mood==='rest'?.90:1)*(dash?1.06:1):0;if(Math.abs(level-this.lastLevel)>.001){this.music.gain.setTargetAtTime(level,t,.18);this.lastLevel=level;}const effectLevel=this.muted?0:this.effectsVolume;if(effectLevel!==this.lastEffects){this.effects.gain.setTargetAtTime(effectLevel,t,.03);this.lastEffects=effectLevel;}const ambient=active&&this.loop&&!this.muted?[.012,.065,.025,.045,.008,.018][this.world]*(.7+.3*Math.sin(t*(this.world===1?.8:.3))):0;this.ambientGain.gain.setTargetAtTime(ambient||0,t,active&&!this.muted?.25:.015);}
 duck(){if(this.context)this.duckUntil=this.context.currentTime+.42;}
 createAmbience(){const c=this.context,b=c.createBuffer(1,c.sampleRate*6,c.sampleRate),d=b.getChannelData(0);let x=0,seed=713;for(let i=0;i<d.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;x=(x+((seed/4294967296)*2-1)*.15)/1.08;d[i]=x;}this.ambient=c.createBufferSource();this.ambient.buffer=b;this.ambient.loop=true;this.ambientFilter=c.createBiquadFilter();this.ambientFilter.type='lowpass';this.ambientFilter.frequency.value=650;this.ambientGain=c.createGain();this.ambientGain.gain.value=0;this.ambient.connect(this.ambientFilter);this.ambientFilter.connect(this.ambientGain);this.ambientGain.connect(this.effects);this.ambient.start();}
 trackEffect(s,nodes=[]){if(this.fx.size>=20){const old=this.fx.values().next().value;try{old.stop();}catch{}this.fx.delete(old);}this.fx.add(s);s.onended=()=>{this.fx.delete(s);s.disconnect();for(const n of nodes)n.disconnect();};}
 stopEffects(){for(const s of this.fx){try{s.stop();}catch{}}this.fx.clear();}
 tone(freq=600,duration=.08,type='sine',volume=.045,glide=0,delay=0){if(this.muted||!this.context||this.context.state!=='running')return;const t=this.context.currentTime+delay,o=this.context.createOscillator(),g=this.context.createGain();o.type=type==='triangle'?'sine':type;o.frequency.setValueAtTime(freq,t);if(glide)o.frequency.exponentialRampToValueAtTime(glide,t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.effects);this.trackEffect(o,[g]);o.start(t);o.stop(t+duration+.02);}
 collect(n){if(!this.context||this.context.currentTime-this.lastCollect<.075)return;this.lastCollect=this.context.currentTime;const root=[523.25,440,587.33,659.25,554.37,523.25][this.world],ratio=[1,1.125,1.25,1.5,1.667][(n-1)%5];this.tone(root*ratio,.13,'sine',.020);this.tone(root*ratio*2,.075,'sine',.004);}
 cue(kind){const base=[523.25,440,587.33,659.25,554.37,523.25][this.world];const patterns={spring:[1,1.5,2],portal:[1,1.25,1.5,2],magnet:[1,1.25,1.5],shield:[1.5,1.25,1],checkpoint:[1,1.5,2],boost:[1,1.25,1.5,2]};(patterns[kind]||patterns.boost).forEach((r,i)=>this.tone(base*r,.23,'sine',.028,0,i*.065));}
 flourish(){this.cue('boost');}
 motion(kind,direction=0){
  const c=this.context;if(this.muted||!c||c.state!=='running')return;
  this.motionTimes??={};const t=c.currentTime;if(t-(this.motionTimes[kind]??-10)<.055)return;this.motionTimes[kind]=t;
  this.motionStep=(this.motionStep??0)+1;const variant=[.94,1.06,.99,1.10,.96][this.motionStep%5],jump=kind==='jump'||kind==='doubleJump';
  const duration=(kind==='slide'?.26:jump?.16:.12)*variant;
  if(!this.airBuffer){this.airBuffer=c.createBuffer(1,Math.ceil(c.sampleRate*.4),c.sampleRate);const d=this.airBuffer.getChannelData(0);let soft=0;for(let i=0;i<d.length;i++){soft=soft*.65+(Math.random()*2-1)*.35;d[i]=soft;}}
  const src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();src.buffer=this.airBuffer;
  f.type='bandpass';f.Q.value=.65;f.frequency.setValueAtTime((kind==='slide'?700:jump?850:1400)*variant,t);f.frequency.exponentialRampToValueAtTime(jump?2100:450,t+duration);
  g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(kind==='slide'?.27:.22,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+duration);
  src.connect(f);f.connect(g);const nodes=[f,g];
  if(c.createStereoPanner){const pan=c.createStereoPanner();pan.pan.setValueAtTime(Math.sign(direction)*.12,t);pan.pan.linearRampToValueAtTime(Math.sign(direction)*.32,t+duration);g.connect(pan);pan.connect(this.effects);nodes.push(pan);}else g.connect(this.effects);
  this.trackEffect(src,nodes);src.start(t);src.stop(t+duration+.02);
  // Soft paw contact and a short upward spring replace the repeated electronic beep.
  if(kind==='lane')this.sample(this.world===3?'snow':'land',.075,variant*[1.2,.92,1.05,1.15,1.35,1.1][this.world]);
  if(jump){const root=[261.63,220,293.66,329.63,277.18,261.63][this.world]*(kind==='doubleJump'?1.5:1);this.tone(root*variant,.14,'sine',.022,root*1.55);this.tone(root*2,.08,'sine',.005,root*2.1,.025);}
 }
 foley(kind){const surface=['land','land','land','snow','snow','land'][this.world],key=kind==='land'?surface:kind,rate=kind==='land'?[1.05,.78,.92,1.05,1.35,1.12][this.world]:1;if(this.sample(key,kind==='smash'?.35:kind==='hit'?.42:kind==='land'?.23:.17,rate))return;this.tone(kind==='hit'?110:kind==='slide'?180:160,.09,'sine',.025,70);}
 loadSamples(){if(this.samplesLoading)return;this.samplesLoading=Promise.allSettled(['land','snow','hit','smash','slide','swipe','star'].map(async key=>{const r=await fetch('assets/sfx/'+key+'.mp3');if(!r.ok)return;this.samples[key]=await this.context.decodeAudioData(await r.arrayBuffer());}));}
 sample(key,volume=.3,rate=1){if(this.muted||!this.context||this.context.state!=='running'||!this.samples[key])return false;const s=this.context.createBufferSource(),g=this.context.createGain();s.buffer=this.samples[key];s.playbackRate.value=rate*(.95+Math.random()*.10);g.gain.value=volume;s.connect(g);g.connect(this.effects);this.trackEffect(s,[g]);s.start();return true;}
}
