import {skillView} from './skill-ui.js?v=touchsound15b';
import * as T from './vendor/three.module.js';
import {SoftwareRenderer} from './software-renderer.js?v=touchsound15b';
import {dog,animateDog,reactDog,ellipsoid,heart,material} from './models.js?v=platform17';
import {Run,LEVELS,WORLDS,LANES,levelData} from './levels.js?v=platform17';
import {RoomEnvironment} from './vendor/RoomEnvironment.js';
import {Juice} from './juice.js?v=touchsound15b';
import {SwipeInput,bindTap,bindPagePause} from './gestures.js?v=touchsound15b';
import {createWorld} from './world.js?v=platform17';
const $=id=>document.getElementById(id),KEY='paws-cloud-3d-v1';
const defaults=()=>({character:'gold',unlocked:0,stars:Array(12).fill(0),records:Array(12).fill(0),wallet:0,music:.55,effects:.45,muted:false,reduced:false,buttons:false});let save=defaults();
try{const v=JSON.parse(localStorage.getItem(KEY)||'null');if(v){save={...save,...v};save.character=['gold','white'].includes(v.character)?v.character:'gold';save.unlocked=Math.min(11,Math.max(0,Math.floor(Number(v.unlocked))||0));save.stars=Array.from({length:12},(_,i)=>Math.max(0,Math.min(3,Math.floor(Number(v.stars?.[i]))||0)));save.records=Array.from({length:12},(_,i)=>Math.max(0,Number(v.records?.[i])||0));save.wallet=Math.max(0,Number(v.wallet)||0);for(const k of ['music','effects'])save[k]=Math.max(0,Math.min(1,Number(v[k])||0));}}catch{$('storageNote').classList.remove('hidden');}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));}catch{$('storageNote').classList.remove('hidden');}}
let renderer,scene,camera,light,world,run=null,mode='home',selected=save.unlocked,last=0,clock=0,petTime=0,viewYaw=0,toastTime=0,countdown=0,settled=false,boneBanked=0,frameSlow=0,quality='high',hudTimer=0,feedbackTime=0,kick=0,cameraReady=false;let cancelSceneInput=()=>{};const dogs={},effects=[],cameraAim=new T.Vector3(),cameraPos=new T.Vector3();
function compactPortrait(){return innerWidth<640||document.documentElement.dataset.phonePortrait==='true';}
const juice=new Juice($('fx'));
const audio=new JourneyAudio('assets/sunny-journey.mp3',()=>notify('音乐暂未加载，可在 ♫ 中重试',4));
function audioMix(){audio.mix({music:save.music,effects:save.effects,muted:save.muted});}
function sound(f=700,d=.1,v=.035,end=0){audio.tone(f,d,'sine',v,end);}
function notify(text,t=2.3){toggle('chapterBanner',false);$('toast').textContent=text;toastTime=t;$('toast').classList.add('show');positionToast();}
function positionToast(){const y=$('hud').offsetTop+$('hud').offsetHeight+8;$('toast').classList.toggle('victory',mode==='clear');$('toast').style.top=mode==='clear'?'max(70px, calc(env(safe-area-inset-top) + 56px))':mode==='running'&&Number.isFinite(y)?y+'px':'';}
function toggle(id,visible){$(id).classList.toggle('hidden',!visible);}
function burst(x,y,z,n=9,color=0xffdc88){juice.emit(x,y,z,color===0xffb08a?'hurt':'gold',save.reduced?Math.min(n,4):n);}
function heartBurst(){for(let i=0;i<5;i++){const m=heart();m.position.set((Math.random()-.5)*2,2.2+Math.random(),.1);m.scale.setScalar(.5+Math.random()*.3);scene.add(m);m.userData={vx:(Math.random()-.5)*.4,vy:1,vz:0,life:1.8};effects.push(m);}}
function setWorld(index){if(world)world.dispose();effects.forEach(m=>{scene.remove(m);if(m.geometry?.type==='ExtrudeGeometry')m.geometry.dispose();});effects.length=0;const w=WORLDS[LEVELS[index].world];$('app').dataset.world=String(LEVELS[index].world);scene.background=new T.Color(w.sky);scene.fog=new T.Fog(w.fog,45,100);world=createWorld(scene,run?.data||levelData(index),{home:!run});light.color.set(LEVELS[index].world===4?0xd9e7ff:0xfff3d6);light.intensity=LEVELS[index].world===4?1.35:1.65;$('musicCredit').textContent='♪ '+w.song;}
function updateHome(){document.querySelectorAll('[data-dog]').forEach(b=>{const active=b.dataset.dog===save.character;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});$('startButton').textContent='出发 · '+LEVELS[selected].name;$('progress').textContent=save.stars.filter(s=>s>0).length+' / 12 关';$('mapButton').firstChild.textContent='旅行地图 · '+(Math.floor(selected/2)+1)+'-'+(selected%2+1)+' ';}
function goHome(){cancelSceneInput();juice.reset();toggle('chapterBanner',false);audio.pause();mode='home';cameraReady=false;$('app').classList.remove('playing');run=null;petTime=0;setWorld(selected);toggle('home',true);toggle('hud',false);toggle('controls',false);toggle('boostStatus',false);toggle('modal',false);toggle('pauseButton',false);toggle('countdown',false);toggle('actionHint',false);$('toast').classList.remove('show');dogs.gold.visible=dogs.white.visible=true;updateHome();persist();}
function start(){cancelSceneInput();juice.reset();audioMix();audio.unlock();mode='running';cameraReady=false;$('app').classList.add('playing');run=new Run(selected,save.character);setWorld(selected);settled=false;boneBanked=0;toggle('home',false);toggle('hud',true);toggle('controls',true);toggle('modal',false);toggle('pauseButton',true);toggle('actionHint',false);audio.setScene?.(run.level.world);audio.setTrack('assets/'+WORLDS[run.level.world].track+'.mp3?v=touchsound15b');audio.unlock();audio.play(true);notify(run.level.lesson,3.7);last=performance.now();hud();}
function hud(){if(!run)return;$('worldLabel').textContent=String(run.level.world+1).padStart(2,'0')+' · '+WORLDS[run.level.world].name;$('levelLabel').textContent=(run.level.world+1)+'-'+(run.level.id%2+1)+' '+run.level.name;$('hearts').textContent='♥ '.repeat(Math.max(0,run.hp))+'♡ '.repeat(3-Math.max(0,run.hp));$('distance').textContent=Math.floor(run.x/run.level.length*100)+'%';$('routeFill').style.width=Math.min(100,run.x/run.level.length*100)+'%';$('starCount').textContent='★ '.repeat(run.stars)+'☆ '.repeat(3-run.stars);$('boneCount').textContent=run.bones;$('combo').textContent='×'+Math.min(5,1+Math.floor(run.combo/4));$('checkpointLabel').textContent=[run.magnetTime>0?'磁铁 '+Math.ceil(run.magnetTime)+'s':'',run.itemShield>0?'护盾 '+Math.ceil(run.itemShield)+'s':''].filter(Boolean).join(' · ')||(run.checkpoint?'已存检查点':'前往终点');$('checkpointLabel').classList.toggle('item-active',run.magnetTime>0||run.itemShield>0);$('swapButton').textContent='⇄ '+(run.character==='gold'?'小金毛':'小白')+'领跑';$('swapButton').disabled=run.powerTime>0||run.swapCooldown>0;updateSkill();$('feverFill').style.width=(run.fever>0?run.fever/4.2:run.charge/28)*100+'%';$('feverLabel').textContent=run.fever>0?'双狗冲刺 · '+run.fever.toFixed(1)+' 秒':'默契 '+run.charge+'/28 · 满格自动冲刺';$('feverTrack').classList.toggle('active',run.fever>0);toggle('boostStatus',run.fever>0);toggle('feverRow',run.fever<=0);$('boostStatus').classList.toggle('ending',run.fever>0&&run.fever<=1.2);$('boostTime').textContent=run.fever.toFixed(1)+'s';$('boostName').textContent=run.fever<=1.2?'冲刺即将结束':'✦ 双狗冲刺 · 无敌收集';$('boostCaption').textContent=run.fever<=1.2?'即将结束 · 看好下一处障碍':'无敌 · 双倍骨头 · 仍可跳跃滑行';$('boostFill').style.width=(run.fever/4.2*100)+'%';$('sectionLabel').textContent=run.section>=0?run.data.sections[run.section].label:'一起出发';positionToast();}
function updateSkill(){
 const v=skillView(run),button=$('powerButton');
 if(button.dataset.state!==v.state||button.dataset.dog!==run.character){
  $('powerAnnounce').textContent=v.name+(v.state==='ready'?'已就绪，点击释放':v.state==='active'?'已释放':'正在冷却');
 }
 button.dataset.state=v.state;button.dataset.dog=run.character;
 button.disabled=v.state!=='ready';button.setAttribute('aria-label',v.label);
 $('powerName').textContent=v.name;$('powerDetail').textContent=v.detail;$('powerState').textContent=v.status;
 $('powerRing').style.background='conic-gradient('+(v.gold?'#a55420':'#187280')+' '+v.progress*360+'deg, #ffffff55 0deg)';
 toggle('powerGold',v.gold);toggle('powerWhite',!v.gold);
}
function openModal(html){$('modalCard').innerHTML=html;toggle('modal',true);$('modalCard').querySelector('button')?.focus();}
function pause(){if(!['running','countdown'].includes(mode))return;cancelSceneInput();mode='paused';audio.pause();toggle('countdown',false);bank();openModal('<span class="eyebrow">A LITTLE PAWS</span><h2 id="modalTitle">小狗歇一会儿</h2><p>当前关卡和音乐已暂停。<br>准备好后，倒数三秒继续。</p><button id="resumeButton" class="primary">继续冒险</button><button id="retryPause" class="secondary">重新挑战这关</button><button id="exitButton" class="text-button">返回旅行地图</button>');$('resumeButton').onclick=resume;$('retryPause').onclick=start;$('exitButton').onclick=()=>{goHome();map();};}
function resume(){if(mode!=='paused')return;mode='countdown';countdown=2.4;toggle('modal',false);toggle('countdown',true);$('countdown').textContent='3';audioMix();audio.unlock();}
function bank(){if(run&&run.bones>boneBanked){save.wallet+=run.bones-boneBanked;boneBanked=run.bones;}persist();}
function clear(){if(settled)return;settled=true;mode='clear';feedbackTime=0;$('impactText').classList.remove('pop');cancelSceneInput();audioMix();audio.victory();bank();const stars=1+(run.stars===3?1:0)+(run.damage===0?1:0),first=save.stars[selected]===0;save.stars[selected]=Math.max(stars,save.stars[selected]);save.records[selected]=Math.max(Math.floor(run.score),save.records[selected]);save.unlocked=Math.max(save.unlocked,Math.min(11,selected+1));if(first)save.wallet+=40;persist();toggle('controls',false);toggle('boostStatus',false);toggle('actionHint',false);toggle('pauseButton',false);toggle('hud',false);toggle('chapterBanner',false);$('toast').classList.remove('show');notify('通关啦！一起欢呼 ♡',2.2);kick=0;setTimeout(()=>{if(mode==='clear')showClear(stars,first);},2200);burst(run.x,2.4,run.z,60,0xffd181);reactDog(dogs.gold,'happy',3);reactDog(dogs.white,'happy',3);}
function showClear(stars,first){const final=selected===11;openModal('<span class="eyebrow">'+(final?'TOGETHER, ALL THE WAY':'A LITTLE VICTORY')+'</span><h2 id="modalTitle">'+(final?'我们一起到家啦！':run.level.name+' · 通关')+'</h2><div class="result-stars">'+'★'.repeat(stars)+'☆'.repeat(3-stars)+'</div><div class="result-stats"><span>旅途星星<b>'+run.stars+' / 3</b></span><span>收集骨头<b>'+run.bones+'</b></span><span>受伤<b>'+run.damage+' 次</b></span></div><p>'+(first?'首次通关 +40 根骨头。':'已保留本关最高星级。')+'<br>★ 抵达终点　★ 找齐三颗星　★ 全程无伤</p><button class="primary" id="nextButton">'+(final?'回到地图 · 收齐 36 星':'下一关 · '+LEVELS[selected+1].name)+'</button><button class="secondary" id="retryClear">重跑本关 · 挑战三星</button><button class="text-button" id="clearMap">旅行地图</button>');$('nextButton').onclick=()=>{if(final){goHome();map();}else{selected++;start();}};$('retryClear').onclick=start;$('clearMap').onclick=()=>{goHome();map();};}
function gameOver(){if(settled)return;settled=true;mode='over';audio.pause();bank();toggle('controls',false);toggle('boostStatus',false);toggle('pauseButton',false);toggle('actionHint',false);openModal('<span class="eyebrow">ONE MORE LITTLE ADVENTURE</span><h2 id="modalTitle">再试一次，我们可以的</h2><div class="result-stats"><span>完成进度<b>'+Math.floor(run.x/run.level.length*100)+'%</b></span><span>星星<b>'+run.stars+'/3</b></span><span>骨头<b>'+run.bones+'</b></span></div><p>左右划换道，上划跳跃，下划滑行；按住拖动也能连续换道。<br>骨头路线会引导你，先稳稳跑过这一关。</p><button id="retryOver" class="primary">再挑战这关</button><button id="overMap" class="secondary">旅行地图</button>');$('retryOver').onclick=start;$('overMap').onclick=()=>{goHome();map();};}
function map(){if(mode!=='home')return;openModal('<span class="eyebrow">TWELVE LITTLE ADVENTURES</span><h2 id="modalTitle">我们的旅行地图</h2><p>十二关，六个世界。弹跳花田、跳岛海岸、树梢高桥、冰隙与星光传送。<br>已收集 '+save.stars.reduce((a,b)=>a+b,0)+' / 36 颗评价星</p>'+WORLDS.map((w,i)=>'<section class="map-world"><h3>'+String(i+1).padStart(2,'0')+' · '+w.name+'</h3><div>'+LEVELS.filter(l=>l.world===i).map(l=>'<button class="level-button '+(l.id===selected?'selected':'')+'" data-level="'+l.id+'" '+(l.id>save.unlocked?'disabled':'')+'>'+(i+1)+'-'+(l.id%2+1)+' '+l.name+'<span>'+(l.id>save.unlocked?'· · ·':'★'.repeat(save.stars[l.id])+'☆'.repeat(3-save.stars[l.id]))+'</span></button>').join('')+'</div></section>').join('')+'<button class="primary" id="closeMap">回到小狗身边</button>');$('modalCard').querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.level);if(i>save.unlocked)return;selected=i;goHome();});$('closeMap').onclick=()=>toggle('modal',false);}
function help(){const prior=mode;if(['running','countdown'].includes(mode))pause();if(['clear','over'].includes(mode))return;openModal('<span class="eyebrow">LET’S GO PLAY</span><h2 id="modalTitle">一起学会冒险</h2><div class="how-list"><div>‹ › <b>单手左右划，立即换道</b><br>三条路线；整排障碍必须跳跃或滑行，空位会随关卡移动。</div><div>↑ <b>上划跳跃，再上划二段跳</b><br>跨过篮子、倒木和浪花；落在篮子或饼干箱顶部会弹起并加分。蓝色骨头位于高桥，沿坡道就能收集。</div><div>↓ <b>下滑或点击滑行</b><br>趴低通过横梁，穿出低障碍后才会起身。冲刺时也能滑行；空中下滑可快速落地。</div><div>✦ <b>两只小狗，各有本领</b><br>点右下方大技能按钮释放：小金毛飞扑破障、吸骨头；小白泡泡吸骨头、挡一次碰撞，并搭桥跨过缺口。按钮显示生效倒数，转圈充满后可再次使用。点 ⇄ 接棒。默契满 28 格自动双狗冲刺 4.2 秒，双倍收集、无敌破障；下方显示剩余时间，结束会提示。</div><div>✿ <b>沿途新发现</b><br>黄色花朵垫踩上自动弹起；同色星门相连。拾取磁铁后吸骨头 6 秒；蓝色护盾在 12 秒内挡一次碰撞。倒计时显示在顶部，护盾不能挡掉落。</div><div>★ <b>每关找三颗星，到旗门就通关</b><br>检查点自动记录。三颗心用完可重试，地图永久保存在当前浏览器。</div><div>键盘：← → 换道 / 空格跳 / ↓ 滑行 / F 技能 / C 接棒 / P 暂停。</div></div><button id="closeHelp" class="primary">'+(prior==='running'?'准备继续':'知道啦')+'</button>');$('closeHelp').onclick=()=>mode==='paused'?resume():toggle('modal',false);}
function settings(){const prior=mode;if(['running','countdown'].includes(mode))pause();if(['clear','over'].includes(mode))return;openModal('<span class="eyebrow">SOUND & FEEL</span><h2 id="modalTitle">舒服地玩</h2><label class="setting-row">音乐<input id="musicVolume" type="range" min="0" max="100" value="'+save.music*100+'"></label><label class="setting-row">音效<input id="effectsVolume" type="range" min="0" max="100" value="'+save.effects*100+'"></label><div class="setting-row"><span>声音</span><button id="muteButton">'+(save.muted?'已静音':'已开启')+'</button></div><div class="setting-row"><span>减少晃动</span><button id="motionButton">'+(save.reduced?'已开启':'未开启')+'</button></div><div class="setting-row"><span>屏幕方向按钮</span><button id="buttonsToggle">'+(save.buttons?'已显示':'手势模式')+'</button></div><div class="sound-library"><p id="listeningLabel" aria-live="polite">♪ 选择一个世界试听</p><div class="sound-choices">'+WORLDS.map((w,i)=>'<button data-score="'+i+'" class="score-choice"><b>'+w.name+'</b><small>'+w.texture+'</small></button>').join('')+'</div><p class="score-credit">配乐：Kevin MacLeod · <a href="https://incompetech.com/" target="_blank" rel="noopener">incompetech.com</a><br><a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a> · 已剪辑、调整响度与淡入淡出。<br><a href="music-credits.html" target="_blank" rel="noopener">曲目与音效署名</a></p></div><button id="closeSettings" class="primary">完成</button>');$('buttonsToggle').onclick=()=>{save.buttons=!save.buttons;document.documentElement.dataset.buttons=String(save.buttons);$('buttonsToggle').textContent=save.buttons?'已显示':'手势模式';persist();};['music','effects'].forEach(k=>$(k+'Volume').oninput=e=>{save[k]=Number(e.target.value)/100;audioMix();persist();});$('muteButton').onclick=()=>{save.muted=!save.muted;$('muteButton').textContent=save.muted?'已静音':'已开启';audioMix();persist();};$('motionButton').onclick=()=>{save.reduced=!save.reduced;$('motionButton').textContent=save.reduced?'已开启':'未开启';document.documentElement.dataset.reduced=String(save.reduced);persist();};$('modalCard').querySelectorAll('[data-score]').forEach(button=>button.onclick=()=>{const i=Number(button.dataset.score);audioMix();audio.setScene?.(i);audio.setTrack('assets/'+WORLDS[i].track+'.mp3?v=touchsound15b');audio.unlock();audio.play(true);$('listeningLabel').textContent='♪ '+WORLDS[i].song;$('modalCard').querySelectorAll('[data-score]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));});$('closeSettings').onclick=()=>{audio.pause();if(mode==='paused'&&run){audio.setScene?.(run.level.world);audio.setTrack('assets/'+WORLDS[run.level.world].track+'.mp3?v=touchsound15b');resume();}else toggle('modal',false);};}
function feedback(text,kind='good'){ $('impactText').textContent=text;$('impactText').dataset.kind=kind;$('impactText').classList.remove('pop');void $('impactText').offsetWidth;$('impactText').classList.add('pop');feedbackTime=.75;}
function handleEvents(){for(const e of run.events){if(e.type==='lane'){audio.motion?.('lane',e.direction);juice.ring(run.x,.05,run.z,'#c6eee6');}if(e.type==='rail'){juice.ring(run.x,run.y+.08,run.z,'#fff0b5');feedback('从前后坡道上下高架');audio.cue?.('rail');}if(e.type==='slide'){juice.pulse('slide');audio.motion?.('slide');burst(run.x-.1,.1,run.z,5,0xffedcb);}if(e.type==='jump'){juice.ring(run.x,Math.max(0,run.y),run.z,e.double?'#a8edff':'#fff2b5');juice.pulse('jump');audio.motion?.(e.double?'doubleJump':'jump');burst(run.x,.2,run.z,5);}if(e.type==='land'){juice.pulse('land');juice.ring(run.x,Math.max(0,run.y)+.02,run.z);audio.foley?.('land');kick=Math.max(kick,e.force*.09);burst(run.x,.08,run.z,7,0xffe4ba);}if(e.type==='bone'){juice.collect(e.item,run);audio.collect?.(run.bones);if(run.bones%5===0)feedback('骨头 +5');}if(e.type==='star'){audio.sample?.('star',.10);reactDog(dogs[run.character],'happy',1.2);juice.pulse('star');juice.ring(e.item.x,e.item.y,e.item.z);feedback('★ 找到星星！','star');sound(1000,.24,.05);burst(e.item.x,e.item.y,e.item.z,12);}if(e.type==='clean'){reactDog(dogs[run.character],'happy',.8);juice.ring(run.x,.12,run.z,'#bcf1d0');feedback(e.combo>1?e.combo+' 连击 · PERFECT':'漂亮！PERFECT');sound(880,.12,.045,1175);}
if(e.type==='stomp'){juice.pulse('land');juice.emit(e.item.x,.8,e.item.z,'smash',28);juice.ring(e.item.x,.88,e.item.z);audio.foley?.('smash');sound(660,.13,.04,980);feedback('踩顶！+80');reactDog(dogs[run.character],'happy',.8);kick=.10;}
if(e.type==='section')audio.setMood?.(e.section.kind);if(e.type==='section'&&toastTime<=0&&run.fever<=0){const b=$('chapterBanner');b.textContent=e.section.label;toggle('chapterBanner',true);b.classList.remove('enter');void b.offsetWidth;b.classList.add('enter');}if(e.type==='fever'){reactDog(dogs[run.character],'happy',1.1);juice.pulse('smash');juice.emit(run.x-.6,.2,run.z,'gold',18);feedback('双狗冲刺 · 4.2 秒','star');notify('默契已满！双狗加入，4.2 秒无敌收集',2.3);audio.flourish?.();}if(e.type==='feverEnd'){feedback('冲刺结束');notify('冲刺结束，恢复正常跑速',1.8);sound(620,.10,.025,430);}if(e.type==='power'){juice.pulse('smash');juice.emit(run.x-.3,.4,run.z,run.character==='white'?'white':'gold',18);reactDog(dogs[run.character],'happy',.7);audio.flourish?.();notify(run.character==='gold'?'小金毛飞扑！障碍让一让':'小白泡泡守护！吸骨头、挡碰撞、搭桥');sound(500,.25,.05,1100);}if(e.type==='swap'){notify(run.character==='gold'?'小金毛接棒！':'小白接棒！');sound(800,.12,.04);}if(e.type==='hurt'){reactDog(dogs[run.character],'hurt',.75);juice.pulse('hurt');audio.foley?.('hit');feedback('哎呀！','hurt');kick=.32;audio.duck();sound(180,.18,.04,90);notify(e.fall?'搭档把你接住了，回到检查点！':'蹭了一下，稳住！');burst(run.x,1,run.z,8,0xffb08a);}if(e.type==='spring'){audio.cue?.('spring');juice.ring(run.x,.12,run.z,'#ffe59e');feedback('花朵弹跳！');}if(e.type==='magnet'||e.type==='shieldOrb'){audio.cue?.(e.type==='magnet'?'magnet':'shield');juice.emit(run.x,.8,run.z,e.type==='magnet'?'gold':'white',16);notify(e.type==='magnet'?'磁铁 6 秒 · 自动吸来骨头':'泡泡护盾 12 秒 · 挡一次碰撞',2.1);}if(e.type==='portal'){audio.cue?.('portal');juice.emit(run.x,1,run.z,'white',22);feedback('星光传送！');}if(e.type==='checkpoint'){bank();notify('检查点亮起了！失误也能从这里继续');sound(870,.18,.04);}if(e.type==='heart')sound(740,.12,.03);if(['smash','shield','itemShieldBlock','protectedSmash'].includes(e.type)){
 const shield=e.type==='shield'||e.type==='itemShieldBlock';kick=0;
 juice.shatter?.(e.item,shield,save.reduced);reactDog(dogs[run.character],'confident',.45);
 if(shield){audio.cue?.('shield');feedback('护盾破障 · 未受伤','star');}
 else{audio.foley?.('smash');feedback(e.type==='smash'?'无敌撞碎！+50':'保护中 · 撞碎障碍','star');}
 }if(e.type==='clear')clear();if(e.type==='over')gameOver();}run.events=[];}
function render(t,dt){if(!renderer)return;if(mode==='home'){light.position.set(8,15,8);light.target.position.set(0,0,0);const mobile=compactPortrait();dogs.gold.visible=dogs.white.visible=true;dogs.gold.position.set(mobile?-1.17:1.35,0,.04);dogs.white.position.set(mobile?1.17:3.75,0,.04);dogs.gold.rotation.y=viewYaw+(mobile?0:.1)+Math.sin(t*.35)*.025;dogs.white.rotation.y=viewYaw+(mobile?0:-.1);for(const d of Object.values(dogs)){d.userData.guard.visible=false;animateDog(d,t,petTime>0?'pet':'idle',{dt});d.scale.setScalar(1.02);}cameraPos.set(mobile?0:7,mobile?2.5:4.0,mobile?10.8:11);cameraAim.set(mobile?0:1.2,mobile?1.22:.9,0);world.update({x:0,time:t},t);}
 else if(run){const active=dogs[run.character],partner=dogs[run.character==='gold'?'white':'gold'];active.visible=true;active.userData.guard.visible=false;active.userData.guard.rotation.y=t*.8;partner.userData.guard.visible=false;partner.visible=run.powerTime>0||run.fever>0||mode==='clear';active.position.set(run.x,run.y,run.z);const landing=Math.sin(run.landPulse/.24*Math.PI);active.scale.set(.86+landing*.035,.86-landing*.065,.86+landing*.035);active.rotation.y=Math.PI/2+(LANES[run.lane]-run.z)*-.12;let pose=mode==='clear'?'cheer':mode==='over'?'idle':run.slideTime>0?'slide':run.jumps>0?'jump':run.boosted?'pounce':'run';animateDog(active,mode==='running'?run.time:t,pose,{dt:run.hitStop>0?0:dt,land:landing,turn:(LANES[run.lane]-run.z)*.45});if(run.jumps===2&&run.y>.3&&run.powerTime===0&&!save.reduced){active.rotation.y+=Math.PI*2*(1-Math.max(0,run.posePulse)/.3);reactDog(active,'happy',.2);}
 if(run.itemShield>0){active.userData.guard.visible=true;active.userData.guard.rotation.y=t*.8;}if(run.hurtTime>0&&!run.boosted&&run.itemShield<=0&&!(run.powerTime>0&&run.powerShield)&&mode==='running')active.userData.rig.rotation.z=Math.sin(t*32)*Math.min(run.hurtTime,.10);
 partner.position.set(run.x+.15,Math.max(0,run.y)*.6,run.z+(run.z<=0?1.35:-1.35));partner.rotation.y=Math.PI/2;partner.scale.setScalar(.72);animateDog(partner,(mode==='running'?run.time:t)+.12,mode==='clear'?'cheer':pose,{dt:run.hitStop>0?0:dt});
 const mobile=compactPortrait(),followDistance=mobile?Math.max(10.6,3.3/(Math.tan(57*Math.PI/360)*camera.aspect)):12.5;cameraPos.set(run.x-followDistance,mobile?4.6:5.5,run.z*.55+.15);cameraAim.set(run.x+(mobile?12:14),.95,run.z*.25);const targetFov=(mobile?57:50)+(run.boosted&&!save.reduced?6:0);camera.fov+=(targetFov-camera.fov)*Math.min(1,dt*6);camera.updateProjectionMatrix();if(mode==='clear'){active.position.set(run.x-.71,0,run.z+.55);partner.position.set(run.x+.71,0,run.z-.55);active.scale.setScalar(.86);partner.scale.setScalar(.86);cameraPos.set(run.x+5.5,3.25,run.z+7.1);cameraAim.set(run.x,1.1,run.z);active.rotation.y=.66;partner.rotation.y=.66;}world.update(run,t);
 const next=run.data.items.find(o=>!o.hit&&!o.taken&&!['bone','star','heart','checkpoint','magnet','shieldOrb','portalExit'].includes(o.type)&&o.x>run.x+1&&o.x<run.x+16&&Math.abs(o.z-run.z)<.9);const gap=run.data.gaps.find(g=>g.a>run.x&&g.a<run.x+15&&(g.lane===undefined||g.lane===run.lane));if(mode==='running'&&(next||gap)){toggle('actionHint',true);$('actionHint').textContent=gap?'断桥 · 上划跳 / 左右绕开':['bar','tunnel'].includes(next.type)?'↓ 下划滑行':['tall','gate'].includes(next.type)?'← → 换到空位':next.type==='portal'?'✦ 走进星门 · 传送到同色门':next.type==='spring'?'✿ 花朵垫 · 踩上自动起跳':next.type==='break'?'↑ 跳过 / 飞扑击碎':'↑ 上划跳跃';}else toggle('actionHint',false);
 light.position.set(run.x+8,15,8);light.target.position.set(run.x+4,0,0);}
 if(!cameraReady){camera.position.copy(cameraPos);cameraReady=true;}else camera.position.lerp(cameraPos,mode==='home'?.12:1);if(!save.reduced){camera.position.y+=Math.sin(t*45)*kick;camera.position.z+=Math.cos(t*39)*kick*.4;}kick=Math.max(0,kick-dt*1.4);camera.lookAt(cameraAim);renderer.render(scene,camera);juice.update(dt,camera,run,mode,save.reduced);}
let fpsStart=0,fpsFrames=0;
function loop(now){fpsFrames++;if(now-fpsStart>2000){document.documentElement.dataset.fps=String(Math.round(fpsFrames*1000/(now-fpsStart)));fpsFrames=0;fpsStart=now;}const dt=Math.min(.06,(now-(last||now))/1000);last=now;clock+=dt;feedbackTime-=dt;if(feedbackTime<=0)$('impactText').classList.remove('pop');petTime=Math.max(0,petTime-dt);toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('show');if(mode==='countdown'){countdown-=dt;$('countdown').textContent=Math.max(1,Math.ceil(countdown/.8));if(countdown<=0){mode='running';toggle('countdown',false);audio.play();}}
 if(mode==='running'&&run){let remaining=dt;while(remaining>0){const step=Math.min(remaining,1/120);run.tick(step);remaining-=step;if(run.state!=='running')break;}handleEvents();hudTimer+=dt;if(hudTimer>.065){hud();hudTimer=0;}}
 for(let i=effects.length-1;i>=0;i--){const m=effects[i],p=m.userData;p.life-=dt;m.position.x+=p.vx*dt;m.position.y+=p.vy*dt;m.position.z+=p.vz*dt;p.vy-=dt*.8;m.scale.multiplyScalar(1-dt*.55);if(p.life<=0){scene.remove(m);if(m.geometry?.type==='ExtrudeGeometry')m.geometry.dispose();effects.splice(i,1);}}
 audio.update(mode==='running'||mode==='clear'&&audio.wantsMusic||audio.wantsMusic&&!$('modal').classList.contains('hidden'),run?.boosted);if(mode!=='paused'&&mode!=='countdown')render(clock,dt);else renderer.render(scene,camera);if(dt>.035&&mode==='running')frameSlow++;else frameSlow=Math.max(0,frameSlow-.3);if(frameSlow>100&&quality==='high'){quality='balanced';renderer.setPixelRatio(1);renderer.shadowMap.enabled=false;}requestAnimationFrame(loop);}
function resize(){if(!renderer)return;const w=$('app').clientWidth,h=$('app').clientHeight;camera.aspect=w/h;camera.fov=compactPortrait()?57:50;cameraReady=false;camera.updateProjectionMatrix();renderer.setSize(w,h,false);juice.resize(w,h);}
function bind(){document.querySelectorAll('[data-dog]').forEach(b=>b.onclick=()=>{save.character=b.dataset.dog;petTime=1.7;updateHome();persist();});$('petButton').onclick=()=>{petTime=3;audioMix();audio.unlock();heartBurst();sound(750,.14,.025);notify(save.character==='gold'?'小金毛：最喜欢和你一起出门！':'小白：再摸摸嘛 ♡',2);};$('turnButton').onclick=()=>{viewYaw+=Math.PI/2;};$('startButton').onclick=start;$('mapButton').onclick=map;bindTap($('pauseButton'),pause);bindTap($('helpButton'),help);bindTap($('audioButton'),settings);$('brand').onclick=()=>{if(['running','countdown','home'].includes(mode))return;goHome();};
 const input=(id,fn)=>$(id).addEventListener('pointerdown',e=>{e.preventDefault();if(mode==='running'){fn();hud();}});input('leftButton',()=>run.laneMove(-1));input('rightButton',()=>run.laneMove(1));input('jumpButton',()=>run.jump());input('slideButton',()=>run.slide());input('powerButton',()=>{run.power();handleEvents();});$('powerButton').addEventListener('click',e=>{if(e.detail===0&&mode==='running'){run.power();handleEvents();hud();}});input('swapButton',()=>run.switch());
 const gesture=new SwipeInput(action=>{if(mode!=='running')return;({left:()=>run.laneMove(-1),right:()=>run.laneMove(1),jump:()=>run.jump(),slide:()=>run.slide()})[action]();hud();});let orbit=null;
 cancelSceneInput=()=>{orbit=null;gesture.cancel();};
 const sceneCanvas=$('scene');
 sceneCanvas.addEventListener('pointerdown',e=>{
  if(e.isPrimary===false||!['home','running'].includes(mode))return;
  cancelSceneInput();
  if(e.cancelable)e.preventDefault();
  if(mode==='home')orbit={x:e.clientX,id:e.pointerId};else gesture.down(e.clientX,e.clientY,e.pointerId);
  try{sceneCanvas.setPointerCapture(e.pointerId);}catch{cancelSceneInput();}
 });
 sceneCanvas.addEventListener('pointermove',e=>{
  if(e.cancelable)e.preventDefault();
  if(mode==='home'&&orbit?.id===e.pointerId){viewYaw+=(e.clientX-orbit.x)*.009;orbit.x=e.clientX;}
  else if(mode==='running')gesture.move(e.clientX,e.clientY,e.pointerId);
 });
 sceneCanvas.addEventListener('pointerup',e=>{
  if(e.cancelable)e.preventDefault();
  if(mode==='running')gesture.up(e.clientX,e.clientY,e.pointerId);
  else if(orbit?.id===e.pointerId)cancelSceneInput();
 });
 for(const event of ['pointercancel','lostpointercapture'])sceneCanvas.addEventListener(event,e=>{
  if(gesture.pointer?.id===e.pointerId||orbit?.id===e.pointerId)cancelSceneInput();
 });
 window.addEventListener('pointerup',e=>{if(gesture.pointer?.id===e.pointerId)gesture.up(e.clientX,e.clientY,e.pointerId);if(orbit?.id===e.pointerId)orbit=null;});
 window.addEventListener('pointercancel',e=>{if(gesture.pointer?.id===e.pointerId||orbit?.id===e.pointerId)cancelSceneInput();});
 sceneCanvas.addEventListener('contextmenu',e=>e.preventDefault());
 $('app').addEventListener('dblclick',e=>{if(e.cancelable)e.preventDefault();});
 // Guard the entire live game document: taps may land on controls or overlays,
 // not just the canvas. Pointer handlers still own gameplay and button activation.
 const blockGameZoom=e=>{if(['running','countdown'].includes(mode)&&e.cancelable)e.preventDefault();};
 for(const type of ['touchstart','touchmove','touchend','gesturestart','gesturechange','gestureend','dblclick'])document.addEventListener(type,blockGameZoom,{capture:true,passive:false});
 // Non-passive touch listeners cover Safari's native gesture arbitration.
 for(const event of ['touchstart','touchmove','touchend'])sceneCanvas.addEventListener(event,e=>{if(['running','home'].includes(mode)&&e.cancelable)e.preventDefault();},{passive:false});
 document.addEventListener('keydown',e=>{if(e.code==='Tab'&&!$('modal').classList.contains('hidden')){const f=[...$('modalCard').querySelectorAll('button:not([disabled]),input')];if(f.length&&e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus();}else if(f.length&&!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus();}return;}if(!['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyF','KeyC','KeyP','Escape'].includes(e.code))return;if(e.target.matches('input'))return;e.preventDefault();if(e.repeat)return;if(e.code==='KeyP'||e.code==='Escape'){mode==='paused'?resume():pause();return;}if(mode!=='running')return;({'Space':()=>run.jump(),'ArrowUp':()=>run.jump(),'ArrowLeft':()=>run.laneMove(-1),'ArrowRight':()=>run.laneMove(1),'ArrowDown':()=>run.slide(),'KeyF':()=>run.power(),'KeyC':()=>run.switch()})[e.code]?.();});
 bindPagePause(document,window,()=>{cancelSceneInput();pause();audio.pause();bank();});window.addEventListener('resize',resize);$('scene').addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('errorMessage').textContent='3D 画面暂时中断，进度已保存。请重新加载。';toggle('error',true);});}
try{try{renderer=new T.WebGLRenderer({canvas:$('scene'),antialias:true,powerPreference:'high-performance',alpha:false});}catch{renderer=new SoftwareRenderer($('scene'));quality='compatible';}renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.35));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;scene=new T.Scene();if(!renderer.software){const pmrem=new T.PMREMGenerator(renderer),studio=new RoomEnvironment();scene.environment=pmrem.fromScene(studio,.04).texture;scene.environmentIntensity=.5;studio.dispose();pmrem.dispose();}camera=new T.PerspectiveCamera(44,1,.1,180);camera.position.set(5,5,12);scene.add(new T.HemisphereLight(0xf3fbff,0xbca58b,.90));light=new T.DirectionalLight(0xfff1d0,1.65);light.position.set(8,15,8);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:.5,far:45});light.shadow.normalBias=.035;scene.add(light,light.target);const fill=new T.DirectionalLight(0xe9eff5,.8);fill.position.set(-8,7,-5);scene.add(fill);dogs.gold=dog('gold',renderer.software);dogs.white=dog('white',renderer.software);scene.add(dogs.gold,dogs.white);setWorld(selected);bind();resize();updateHome();document.documentElement.dataset.buttons=String(save.buttons);document.documentElement.dataset.reduced=String(save.reduced);$('startButton').disabled=false;document.documentElement.dataset.ready='true';document.documentElement.dataset.renderer=renderer.software?'compatible':'webgl';toggle('error',false);requestAnimationFrame(loop);}catch(e){console.error(e);$('errorMessage').textContent='无法启动 3D 画面。请用 Safari 或 Chrome 打开，并刷新页面重试。';toggle('error',true);}
